language: node_js
node_js:
  - 6.10.2
before_script:
  - npm install
  - npm install -g bower
  - bower install
services: 
  - mongodb
script: 
  - npm run coverage
after_success:
  - "cat ./coverage/lcov.info | coveralls"
  